from ai_assistant import generate_attendance_summary
import os
import csv
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
# Date
today = datetime.now().strftime("%d-%m-%Y")

attendance_file = os.path.join(
    "Attendance",
    f"Attendance_{today}.csv"
)
# Reports Folder
if not os.path.exists("reports"):
    os.makedirs("reports")

pdf_file = os.path.join(
    "reports",
    f"Attendance_Report_{today}.pdf"
)
# Check Attendance File
if not os.path.exists(attendance_file):
    print("Attendance File Not Found!")
    exit()
# Read CSV
data = []

with open(attendance_file, "r", newline="") as file:

    reader = csv.reader(file)

    for row in reader:
        data.append(row)

total_present = len(data) - 1
# ==========================================
# AI Attendance Summary
# ==========================================

total_students = 50   
attendance_percentage = round(
    (total_present / total_students) * 100,
    2
)

try:

    ai_summary = generate_attendance_summary(
        "Entire Class",
        attendance_percentage
    )

except Exception as e:

    ai_summary = f"AI Summary Not Available\n\n{e}"

# ==========================================
# PDF
# ==========================================

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER

doc = SimpleDocTemplate(pdf_file)

elements = []

# ==========================================
# Title
# ==========================================

elements.append(
    Paragraph(
        "AI SMART ATTENDANCE SYSTEM",
        title_style
    )
)

elements.append(Spacer(1, 10))

elements.append(
    Paragraph(
        "<b>Attendance Report</b>",
        styles["Heading2"]
    )
)

elements.append(
    Paragraph(
        f"Date : {today}",
        styles["Normal"]
    )
)

elements.append(
    Paragraph(
        f"Total Present Students : {total_present}",
        styles["Normal"]
    )
)

elements.append(Spacer(1, 15))

# ==========================================
# Table
# ==========================================

table = Table(data)

table.setStyle(

    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.darkblue),

        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 1, colors.black),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("ALIGN", (0,0), (-1,-1), "CENTER"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("TOPPADDING", (0,1), (-1,-1), 8)

    ])

)

elements.append(table)

elements.append(Spacer(1, 20))
# ==========================================
# AI Summary
# ==========================================

elements.append(

    Paragraph(
        "<b>Generative AI Attendance Analysis</b>",
        styles["Heading2"]
    )

)

elements.append(
    Spacer(1, 10)
)

elements.append(

    Paragraph(
        ai_summary.replace("\n", "<br/>"),
        styles["BodyText"]
    )

)

elements.append(
    Spacer(1, 20)
)

# ==========================================
# Footer
# ==========================================

elements.append(
    Paragraph(
        "Generated By : AI Smart Attendance Monitoring System",
        styles["Italic"]
    )
)

doc.build(elements)

print("="*45)
print("PDF Report Generated Successfully")
print(pdf_file)
print("="*45)